cmake_path(NATIVE_PATH CMAKE_CURRENT_SOURCE_DIR NORMALIZE DIR)
string(REPLACE "\\" "\\\\" ESCAPE_DIR ${DIR})

execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse HEAD
    OUTPUT_STRIP_TRAILING_WHITESPACE
    OUTPUT_VARIABLE GIT_HASH
    COMMAND_ERROR_IS_FATAL ANY
)

configure_file(${TEMPLATE} ${OUTPUT})
